import "./globals.css";
import Navbar from "src/components/Navbar";
import Footer from "src/components/Footer";

export const metadata = {
  title: "IEEE_Official_Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <div className="pt-20">
        {children}
        </div>
        <Footer/>
      </body>
    </html>
  );
}